//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace ElectronTransferView.CadService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ElectronTransferServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ElectronTransferService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DisableTicket1OperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableTicket3OperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableTicket2OperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckTickesOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpenTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishAppendOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpLoadAppendOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownByKXOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDownStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownByFWOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownByKXandFWOperationCompleted;
        
        private System.Threading.SendOrPostCallback fireEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback endFireEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableTicketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ElectronTransferService() {
            this.Url = global::ElectronTransferView.Properties.Settings.Default.ElectronTransferView_CadService_ElectronTransferService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DisableTicket1CompletedEventHandler DisableTicket1Completed;
        
        /// <remarks/>
        public event DisableTicket3CompletedEventHandler DisableTicket3Completed;
        
        /// <remarks/>
        public event DisableTicket2CompletedEventHandler DisableTicket2Completed;
        
        /// <remarks/>
        public event CheckTickesCompletedEventHandler CheckTickesCompleted;
        
        /// <remarks/>
        public event OpenTicketCompletedEventHandler OpenTicketCompleted;
        
        /// <remarks/>
        public event PublishAppendCompletedEventHandler PublishAppendCompleted;
        
        /// <remarks/>
        public event UpLoadAppendCompletedEventHandler UpLoadAppendCompleted;
        
        /// <remarks/>
        public event DownByKXCompletedEventHandler DownByKXCompleted;
        
        /// <remarks/>
        public event CheckDownStateCompletedEventHandler CheckDownStateCompleted;
        
        /// <remarks/>
        public event DownByFWCompletedEventHandler DownByFWCompleted;
        
        /// <remarks/>
        public event DownByKXandFWCompletedEventHandler DownByKXandFWCompleted;
        
        /// <remarks/>
        public event fireEventCompletedEventHandler fireEventCompleted;
        
        /// <remarks/>
        public event endFireEventCompletedEventHandler endFireEventCompleted;
        
        /// <remarks/>
        public event DisableTicketCompletedEventHandler DisableTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableTicket1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DisableTicket1(string GC_ID) {
            object[] results = this.Invoke("DisableTicket1", new object[] {
                        GC_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DisableTicket1Async(string GC_ID) {
            this.DisableTicket1Async(GC_ID, null);
        }
        
        /// <remarks/>
        public void DisableTicket1Async(string GC_ID, object userState) {
            if ((this.DisableTicket1OperationCompleted == null)) {
                this.DisableTicket1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableTicket1OperationCompleted);
            }
            this.InvokeAsync("DisableTicket1", new object[] {
                        GC_ID}, this.DisableTicket1OperationCompleted, userState);
        }
        
        private void OnDisableTicket1OperationCompleted(object arg) {
            if ((this.DisableTicket1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableTicket1Completed(this, new DisableTicket1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableTicket3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DisableTicket3(string[] FNOFIDS, string gc_id) {
            object[] results = this.Invoke("DisableTicket3", new object[] {
                        FNOFIDS,
                        gc_id});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DisableTicket3Async(string[] FNOFIDS, string gc_id) {
            this.DisableTicket3Async(FNOFIDS, gc_id, null);
        }
        
        /// <remarks/>
        public void DisableTicket3Async(string[] FNOFIDS, string gc_id, object userState) {
            if ((this.DisableTicket3OperationCompleted == null)) {
                this.DisableTicket3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableTicket3OperationCompleted);
            }
            this.InvokeAsync("DisableTicket3", new object[] {
                        FNOFIDS,
                        gc_id}, this.DisableTicket3OperationCompleted, userState);
        }
        
        private void OnDisableTicket3OperationCompleted(object arg) {
            if ((this.DisableTicket3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableTicket3Completed(this, new DisableTicket3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableTicket2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DisableTicket2(string[] FNOFIDS) {
            object[] results = this.Invoke("DisableTicket2", new object[] {
                        FNOFIDS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DisableTicket2Async(string[] FNOFIDS) {
            this.DisableTicket2Async(FNOFIDS, null);
        }
        
        /// <remarks/>
        public void DisableTicket2Async(string[] FNOFIDS, object userState) {
            if ((this.DisableTicket2OperationCompleted == null)) {
                this.DisableTicket2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableTicket2OperationCompleted);
            }
            this.InvokeAsync("DisableTicket2", new object[] {
                        FNOFIDS}, this.DisableTicket2OperationCompleted, userState);
        }
        
        private void OnDisableTicket2OperationCompleted(object arg) {
            if ((this.DisableTicket2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableTicket2Completed(this, new DisableTicket2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckTickes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckTickes(string[] GC_FNOFIDS) {
            object[] results = this.Invoke("CheckTickes", new object[] {
                        GC_FNOFIDS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckTickesAsync(string[] GC_FNOFIDS) {
            this.CheckTickesAsync(GC_FNOFIDS, null);
        }
        
        /// <remarks/>
        public void CheckTickesAsync(string[] GC_FNOFIDS, object userState) {
            if ((this.CheckTickesOperationCompleted == null)) {
                this.CheckTickesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTickesOperationCompleted);
            }
            this.InvokeAsync("CheckTickes", new object[] {
                        GC_FNOFIDS}, this.CheckTickesOperationCompleted, userState);
        }
        
        private void OnCheckTickesOperationCompleted(object arg) {
            if ((this.CheckTickesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTickesCompleted(this, new CheckTickesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OpenTicket(string[] GC_FNOFIDS, string GC_UserName, string GC_ID) {
            object[] results = this.Invoke("OpenTicket", new object[] {
                        GC_FNOFIDS,
                        GC_UserName,
                        GC_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OpenTicketAsync(string[] GC_FNOFIDS, string GC_UserName, string GC_ID) {
            this.OpenTicketAsync(GC_FNOFIDS, GC_UserName, GC_ID, null);
        }
        
        /// <remarks/>
        public void OpenTicketAsync(string[] GC_FNOFIDS, string GC_UserName, string GC_ID, object userState) {
            if ((this.OpenTicketOperationCompleted == null)) {
                this.OpenTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenTicketOperationCompleted);
            }
            this.InvokeAsync("OpenTicket", new object[] {
                        GC_FNOFIDS,
                        GC_UserName,
                        GC_ID}, this.OpenTicketOperationCompleted, userState);
        }
        
        private void OnOpenTicketOperationCompleted(object arg) {
            if ((this.OpenTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenTicketCompleted(this, new OpenTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublishAppend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PublishAppend(string GC_ID) {
            object[] results = this.Invoke("PublishAppend", new object[] {
                        GC_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PublishAppendAsync(string GC_ID) {
            this.PublishAppendAsync(GC_ID, null);
        }
        
        /// <remarks/>
        public void PublishAppendAsync(string GC_ID, object userState) {
            if ((this.PublishAppendOperationCompleted == null)) {
                this.PublishAppendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishAppendOperationCompleted);
            }
            this.InvokeAsync("PublishAppend", new object[] {
                        GC_ID}, this.PublishAppendOperationCompleted, userState);
        }
        
        private void OnPublishAppendOperationCompleted(object arg) {
            if ((this.PublishAppendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishAppendCompleted(this, new PublishAppendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadAppend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpLoadAppend(string AppendFile, string GC_ID) {
            object[] results = this.Invoke("UpLoadAppend", new object[] {
                        AppendFile,
                        GC_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpLoadAppendAsync(string AppendFile, string GC_ID) {
            this.UpLoadAppendAsync(AppendFile, GC_ID, null);
        }
        
        /// <remarks/>
        public void UpLoadAppendAsync(string AppendFile, string GC_ID, object userState) {
            if ((this.UpLoadAppendOperationCompleted == null)) {
                this.UpLoadAppendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadAppendOperationCompleted);
            }
            this.InvokeAsync("UpLoadAppend", new object[] {
                        AppendFile,
                        GC_ID}, this.UpLoadAppendOperationCompleted, userState);
        }
        
        private void OnUpLoadAppendOperationCompleted(object arg) {
            if ((this.UpLoadAppendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadAppendCompleted(this, new UpLoadAppendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownByKX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownByKX(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            object[] results = this.Invoke("DownByKX", new object[] {
                        SSDW_ID,
                        KX_ID,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownByKXAsync(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            this.DownByKXAsync(SSDW_ID, KX_ID, ZYDY, GC_ID, SESSION_ID, FidFnoList, null);
        }
        
        /// <remarks/>
        public void DownByKXAsync(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList, object userState) {
            if ((this.DownByKXOperationCompleted == null)) {
                this.DownByKXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownByKXOperationCompleted);
            }
            this.InvokeAsync("DownByKX", new object[] {
                        SSDW_ID,
                        KX_ID,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList}, this.DownByKXOperationCompleted, userState);
        }
        
        private void OnDownByKXOperationCompleted(object arg) {
            if ((this.DownByKXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownByKXCompleted(this, new DownByKXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDownState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckDownState(string SESSION_ID) {
            object[] results = this.Invoke("CheckDownState", new object[] {
                        SESSION_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDownStateAsync(string SESSION_ID) {
            this.CheckDownStateAsync(SESSION_ID, null);
        }
        
        /// <remarks/>
        public void CheckDownStateAsync(string SESSION_ID, object userState) {
            if ((this.CheckDownStateOperationCompleted == null)) {
                this.CheckDownStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDownStateOperationCompleted);
            }
            this.InvokeAsync("CheckDownState", new object[] {
                        SESSION_ID}, this.CheckDownStateOperationCompleted, userState);
        }
        
        private void OnCheckDownStateOperationCompleted(object arg) {
            if ((this.CheckDownStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDownStateCompleted(this, new CheckDownStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownByFW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownByFW(double Xmin, double Xmax, double Ymin, double Ymax, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            object[] results = this.Invoke("DownByFW", new object[] {
                        Xmin,
                        Xmax,
                        Ymin,
                        Ymax,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownByFWAsync(double Xmin, double Xmax, double Ymin, double Ymax, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            this.DownByFWAsync(Xmin, Xmax, Ymin, Ymax, ZYDY, GC_ID, SESSION_ID, FidFnoList, null);
        }
        
        /// <remarks/>
        public void DownByFWAsync(double Xmin, double Xmax, double Ymin, double Ymax, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList, object userState) {
            if ((this.DownByFWOperationCompleted == null)) {
                this.DownByFWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownByFWOperationCompleted);
            }
            this.InvokeAsync("DownByFW", new object[] {
                        Xmin,
                        Xmax,
                        Ymin,
                        Ymax,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList}, this.DownByFWOperationCompleted, userState);
        }
        
        private void OnDownByFWOperationCompleted(object arg) {
            if ((this.DownByFWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownByFWCompleted(this, new DownByFWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownByKXandFW", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownByKXandFW(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            object[] results = this.Invoke("DownByKXandFW", new object[] {
                        SSDW_ID,
                        KX_ID,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownByKXandFWAsync(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList) {
            this.DownByKXandFWAsync(SSDW_ID, KX_ID, ZYDY, GC_ID, SESSION_ID, FidFnoList, null);
        }
        
        /// <remarks/>
        public void DownByKXandFWAsync(string SSDW_ID, string KX_ID, string ZYDY, string GC_ID, string SESSION_ID, string[] FidFnoList, object userState) {
            if ((this.DownByKXandFWOperationCompleted == null)) {
                this.DownByKXandFWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownByKXandFWOperationCompleted);
            }
            this.InvokeAsync("DownByKXandFW", new object[] {
                        SSDW_ID,
                        KX_ID,
                        ZYDY,
                        GC_ID,
                        SESSION_ID,
                        FidFnoList}, this.DownByKXandFWOperationCompleted, userState);
        }
        
        private void OnDownByKXandFWOperationCompleted(object arg) {
            if ((this.DownByKXandFWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownByKXandFWCompleted(this, new DownByKXandFWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fireEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void fireEvent(string eventname) {
            this.Invoke("fireEvent", new object[] {
                        eventname});
        }
        
        /// <remarks/>
        public void fireEventAsync(string eventname) {
            this.fireEventAsync(eventname, null);
        }
        
        /// <remarks/>
        public void fireEventAsync(string eventname, object userState) {
            if ((this.fireEventOperationCompleted == null)) {
                this.fireEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfireEventOperationCompleted);
            }
            this.InvokeAsync("fireEvent", new object[] {
                        eventname}, this.fireEventOperationCompleted, userState);
        }
        
        private void OnfireEventOperationCompleted(object arg) {
            if ((this.fireEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fireEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/endFireEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void endFireEvent(string eventname) {
            this.Invoke("endFireEvent", new object[] {
                        eventname});
        }
        
        /// <remarks/>
        public void endFireEventAsync(string eventname) {
            this.endFireEventAsync(eventname, null);
        }
        
        /// <remarks/>
        public void endFireEventAsync(string eventname, object userState) {
            if ((this.endFireEventOperationCompleted == null)) {
                this.endFireEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnendFireEventOperationCompleted);
            }
            this.InvokeAsync("endFireEvent", new object[] {
                        eventname}, this.endFireEventOperationCompleted, userState);
        }
        
        private void OnendFireEventOperationCompleted(object arg) {
            if ((this.endFireEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.endFireEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisableTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DisableTicket() {
            object[] results = this.Invoke("DisableTicket", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DisableTicketAsync() {
            this.DisableTicketAsync(null);
        }
        
        /// <remarks/>
        public void DisableTicketAsync(object userState) {
            if ((this.DisableTicketOperationCompleted == null)) {
                this.DisableTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableTicketOperationCompleted);
            }
            this.InvokeAsync("DisableTicket", new object[0], this.DisableTicketOperationCompleted, userState);
        }
        
        private void OnDisableTicketOperationCompleted(object arg) {
            if ((this.DisableTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableTicketCompleted(this, new DisableTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DisableTicket1CompletedEventHandler(object sender, DisableTicket1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableTicket1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableTicket1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DisableTicket3CompletedEventHandler(object sender, DisableTicket3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableTicket3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableTicket3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DisableTicket2CompletedEventHandler(object sender, DisableTicket2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableTicket2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableTicket2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckTickesCompletedEventHandler(object sender, CheckTickesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTickesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTickesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void OpenTicketCompletedEventHandler(object sender, OpenTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PublishAppendCompletedEventHandler(object sender, PublishAppendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishAppendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishAppendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpLoadAppendCompletedEventHandler(object sender, UpLoadAppendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpLoadAppendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpLoadAppendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownByKXCompletedEventHandler(object sender, DownByKXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownByKXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownByKXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckDownStateCompletedEventHandler(object sender, CheckDownStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDownStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDownStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownByFWCompletedEventHandler(object sender, DownByFWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownByFWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownByFWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownByKXandFWCompletedEventHandler(object sender, DownByKXandFWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownByKXandFWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownByKXandFWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void fireEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void endFireEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DisableTicketCompletedEventHandler(object sender, DisableTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591